security:
  authentication:
    logoutUrl: /api/v1/auth/logout

  oauth2:
    loginEndpointBaseUri: /api/v1/auth/oauth2/authorization
    loginRedirectionEndpointBaseUri: /api/v1/auth/oauth2/redirection-endpoint