server:
  port: 8080

  # UTF-8 사용
  servlet:
    session:
      cookie:
        domain: hirecruit.site
        max-age: P1D # 1일
        secure: true
        same-site: none
      timeout: 1440m # 1440분 = 1일

spring:
  config:
    import:
    classpath:oauth/github-oauth.yml
    optional:file:prod.env[properties]

  mvc:
    path match:
      matching-strategy: ant_path_matcher

  # oauth2 redirect-uri
  security:
    oauth2:
      client:
        registration:
          github:
            redirect-uri: https://server.hirecruit.site/api/v1/auth/oauth2/redirection-endpoint

  session:
    store-type: redis
    redis:
      flush-mode: immediate
      namespace: spring:session # redis에 세션 저장시 네임스페이스

  #DB 설정
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  redis:
    host: ${redis.host}
    password: ${redis.password}
    port: ${redis.port}

### Logging ###
logging:
  level:
    site.hirecruit.hr : info

oauth2.login.success.redirect-base-uri: https://www.hirecruit.site
hr.domain: hirecruit.site