.env:
  filename: .env.staging
  prefix: ""

server:
  port: 8080

  # UTF-8 사용
  servlet:
    session:
      cookie:
        domain: hirecruit.site
        max-age: P1D # 1일
        secure: true
        same-site: none
        name: HRSESSION
      timeout: 1440m # 1440분 = 1일

spring:
  config:
    import:
      - classpath:oauth/github-oauth-staging.yml
      - classpath:properties/security.yml

  batch:
    job:
      enabled: false

  mvc:
    path match:
      matching-strategy: ant_path_matcher

  # oauth2 redirect-uri
  security:
    oauth2:
      client:
        registration:
          github:
            redirect-uri: https://stg.hirecruit.site/api/v1/auth/oauth2/redirection-endpoint

  session:
    store-type: redis
    redis:
      flush-mode: immediate
      namespace: spring:session:staging # redis에 세션 저장시 네임스페이스

  redis:
    host: ${REDIS_HOST}
    password:
    port: 6379

  #H2 DataBase
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  #DB 설정
  datasource:
    url: jdbc:h2:mem:HR
    driver-class-name: org.h2.Driver
    username: sa

  ### JPA 설정 ###
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: create
    show-sql: true

### Logging ###
logging:
  level:
    org.hibernate.type.descriptor.sql : trace
    site.hirecruit.hr : debug
  config: classpath:logback/logback-staging.xml

oauth2.login.success.redirect-base-uri: https://dev.hirecruit.site
hr.domain: hirecruit.site