server:
  port: 8080

  # UTF-8 사용
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

    session:
      cookie:
        domain:
          - www.hirecruit.com
          - stg.hirecruit.com
          - localhost
        max-age: 36000

spring:
  config:
    import: classpath:oauth/github-oauth.yml

  # oauth2 redirect-uri
  security:
    oauth2:
      client:
        registration:
          github:
            redirect-uri: http://localhost:8080/api/v1/auth/oauth2/redirection-endpoint

  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring:session # redis에 세션 저장시 네임스페이스

  redis:
    host: localhost
    password:
    port: 6379

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  #H2 DataBase
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  #DB 설정
  datasource:
    url: jdbc:h2:mem:HR
    driver-class-name: org.h2.Driver
    username: sa

  ### JPA 설정 ###
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: create
    show-sql: true

### Logging ###
logging:
  level:
    org.hibernate.type.descriptor.sql : trace
    site.hirecruit.hr : debug

oauth2.login.success.redirect-base-uri: http://localhost:3000