server:
  port: 8080

  # UTF-8 사용
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  config:
    import: classpath:oauth/github-oauth.yml

  redis:
    host: localhost
    password:
    port: 6379

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  #H2 DataBase
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  #DB 설정
  datasource:
    url: jdbc:h2:mem:HR
    driver-class-name: org.h2.Driver
    username: sa

  ### JPA 설정 ###
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: create
    show-sql: true

### Logging ###
logging:
  level:
    org.hibernate.type.descriptor.sql : trace
    site.hirecruit.hr : debug
